config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :beers
    resources :beer_likes
    resources :breweries

    root to: "users#index"
  end

  resources :beers do
    resources :comments, only: [:create, :index, :destroy]
    member do
      get :like, :unlike
    end
  end
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :breweries

  resources :users, only: [:show], as: "/users/{:username}", as: "show_profile"


  match '/clear' => 'brewery_admin#clear', :via => 'get'
  match '/search' => "pages#search", :via => 'get', :as => "search"
  
  match '/:id' => "breweries#show", :via => 'get', :as => "main_brewery"
  match '/:brewery/beer/:id' => "beers#show", :via => 'get', :as => "main_beer"
  match '/:brewery/admin' => 'pages#index', :via => 'get'
  match '/:brewery/admin/:token' => "brewery_admin#index", :via => 'get', :as => "brewery_admin"
  match '/:brewery/admin/:beer/edit/:token' => "brewery_admin#edit", :via => 'get', :as => "brewery_edit"
 

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brewery.rb
class Brewery < ApplicationRecord
    searchkick
    
    before_save :update_slug
    validates :slug, uniqueness: { case_sensitive: false }

    mount_uploader :brewery_logo, BreweryLogoUploader, mount_on: :brewery_logo_file_name
    has_many :beers, :dependent => :destroy
    accepts_nested_attributes_for :beers

    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    before_create :add_token

    def address
    [address1, address2, city, county, postcode, country].compact.join(', ')
    end

    def address_changed?
        address1_changed? || address2_changed? || city_changed? || county_changed? || postcode_changed? || country_changed?
    end

    def update_slug
        self.slug = name.parameterize
    end

    def add_token
        self.token = SecureRandom.hex
      end

end

app/controllers/admin/breweries_controller.rb
module Admin
  class BreweriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Brewery.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Brewery.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show]
  before_action :set_brewery_id, only: [:edit, :update, :destroy]
  before_action :must_be_admin, only: [:edit, :new]

  

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all.page(params[:page]).per(12)
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to main_brewery_path(@brewery.slug), notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to main_brewery_path(@brewery.slug), notice: 'Brewery was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find_by(slug: params[:id])
    end

    def set_brewery_id
      @brewery = Brewery.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :address1, :address2, :city, :county, :postcode, :country, :email, :telephone, :website, :description, :brewery_logo, :slug, :latitude, :longitude, :twitter, :facebook, :instagram)
    end

    def must_be_admin
      unless current_user && current_user.admin?
        redirect_to new_user_session_path
      end
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery-show-sidebar.html.erb
    <img src="<%= @brewery.brewery_logo.thumb %>" alt="<%= @brewery.name %>" class="img-thumbnail beer-img" style="<%= brewery_colour_border(@brewery) %>">

    <div class="sidebar">
        <div class="sidebar-title">
        <%= @brewery.name %>
        </div>
    </div>

    <div class="sidebar">
        <div class="sidebar-title brewery-percentage-vegan">
            <%= percentage_vegan(@brewery) %> of Beers Vegan
        </div>
    </div>

    <div class="sidebar-item-container">
        <div class="sidebar-item brewery-location">
            <%= @brewery.city %>, <%= @brewery.country %>
        </div>

        <div class="sidebar-item brewery-website">
            <a href="http://<%= @brewery.website %>"><%= @brewery.website %></a>
        </div>
        <div class="sidebar-item brewery-telephone">
            <a href="tel://<%= @brewery.telephone %>"><%= @brewery.telephone %></a>
        </div>
        <div class="sidebar-item brewery-email">
            <a href="mailto://<%= @brewery.email %>"><%= @brewery.email %></a>
        </div>
    </div>

    <div class="sidebar-item-container">
        <div class="sidebar-item brewery-facebook">
            <a href="http://facebook.com/<%= @brewery.facebook %>">Facebook</a>
        </div>
        <div class="sidebar-item brewery-instagram">
            <a href="http://instagram.com/<%= @brewery.instagram %>">Instagram</a>
        </div>
        <div class="sidebar-item brewery-twitter">
            <a href="http://twitter.com/<%= @brewery.twitter %>">Twitter</a>
        </div>
    </div>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery, local: true, multipart: true) do |form| %>
  <% if brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :brewery_name %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :brewery_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :brewery_address2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :brewery_city %>
  </div>

  <div class="field">
    <%= form.label :county_state %>
    <%= form.text_field :county, id: :brewery_county_state %>
  </div>

  <div class="field">
    <%= form.label :zip_postcode %>
    <%= form.text_field :postcode, id: :brewery_zip_postcode %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :brewery_country %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :brewery_country %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone, id: :brewery_country %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :brewery_country %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :brewery_description %>
  </div>

  <div class="field">
    <%= form.label :brewery_logo %>
    <%= form.file_field :brewery_logo, id: :brewery_brewery_logo %>
  </div>

  <div class="field">
    <%= form.label :instagram %>
    <%= form.text_field :instagram, id: :brewery_zip_postcode %>
  </div>

  <div class="field">
    <%= form.label :facebook %>
    <%= form.text_field :facebook, id: :brewery_zip_postcode %>
  </div>

  <div class="field">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, id: :brewery_zip_postcode %>
  </div>
  <br/>

  <div class="field">
    <%= form.text_field :latitude, id: :brewery_latitude, :hidden => true %>
  </div>

  <div class="field">
    <%= form.text_field :longitude, id: :brewery_longitude, :hidden => true %>
  </div>

  <div class="field">
    <%= form.text_field :slug, id: :brewery_country, :hidden => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<div class="main-container">
<section class="space--xs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>Edit Brewery</h1>
                        </div>
                    </div>
                </div>
</section>
<section class="space--xs">
    <div class="container">
        <%= render 'form', brewery: @brewery %>
    </div>
</section>
<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<%- title "Which of these breweries are vegan?" %>
<div class="main-container">
  <%= render 'layouts/searchbar' %>

  <section class="space--xxs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>Breweries</h1>
                            <ol class="breadcrumbs">
                                <li><a href="#">Home</a></li>
                                <li>Breweries</li>
                            </ol></div>
                    </div>
                </div>
            </section>

            <section class="bg--secondary space--xxs">
                <div class="container">
                <%= paginate(@breweries) %>
                    <div class="masonry">
                        <div class="masonry__container row masonry--active">
                        <% @breweries.each do |brewery| %>
                        
                            <div class="col-md-4 masonry__item">
                                <div class="card card-2 text-center">
                                    <div class="card__top">
                                        <%= link_to main_brewery_path(brewery.slug) do %><img alt="Image" src="<%= brewery.brewery_logo.thumb %>"><% end %>
                                    </div>
                                    <div class="card__body">
                                    <%= link_to main_brewery_path(brewery.slug) do %>
                                        <h4><%= brewery.name %></h4> <span class="type--fade"><%= brewery.city %>, <%= brewery.country %></span> </div>
                                    <% end %>
                                </div>
                            </div>
                        
                        <% end %>
                        </div>
                    </div>
                    <%= paginate(@breweries) %>
                </div>
            </section>

app/views/breweries/new.html.erb
<div class="main-container">
<section class="space--xs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>New Brewery</h1>
                        </div>
                    </div>
                </div>
</section>
<section class="space--xs">
    <div class="container">
        <%= render 'form', brewery: @brewery %>
    </div>
</section>



<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<%- title "Are #{@brewery.name} Beers Vegan?" %>

<div class="main-container">
  <%= render 'layouts/searchbar' %>

  <section class="space--xxs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1><%= @brewery.name %></h1>
                            <ol class="breadcrumbs">
                                <li><a href="#">Home</a></li>
                                <li><%= link_to "Breweries", breweries_path %></li>
                                <li><%= link_to @brewery.name, main_brewery_path(@brewery.slug) %></li>
                            </ol></div>
                    </div>
                </div>
            </section>

<section class="bg--secondary space--xxs">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-lg-3">
        <div class="card card-2 text-center" style="margin-bottom: 3em;">
          <div class="card__top">
            <a href="#"> <img alt="Image" src="<%= @brewery.brewery_logo.thumb %>"> </a>
          </div>
        </div>
        <div class="text-block side-bar-info">
          <h5> <%= percentage_vegan(@brewery) %> of Beers Vegan </h5>
        </div>
        <div class="text-block side-bar-info">
          <h5>City</h5>
          <hr/>
          <p> <%= @brewery.city %>, <%= @brewery.country %> </p>
        </div>
        <% if @brewery.website.present?%>
        <div class="text-block side-bar-info">
          <h5>Website</h5>
          <hr/>
          <p><a href="http://<%= @brewery.website %>"><%= @brewery.website %></a> </p>
        </div>
        <% end %>
        <div class="text-block side-bar-info social-media-side">
          <h5>Social Media</h5>
          <hr/>
          <p style="font-size: 3em;"> 
            <% if @brewery.facebook.present?%>
            <a href="http://facebook.com/<%= @brewery.facebook %>">
              <i class="fab fa-facebook-square"></i>
            </a>
            <% end %>
            <% if @brewery.twitter.present?%>
            <a href="http://twitter.com/<%= @brewery.twitter %>">
              <i class="fab fa-twitter-square"></i>
            </a>
            <% end %>
            <% if @brewery.instagram.present?%>
            <a href="http://instagram.com/<%= @brewery.instagram %>">
              <i class="fab fa-instagram"></i>
            </a>
            <% end %>
          </p>
        </div>
      </div>
      <div class="col-md-8 col-lg-9">
      <%= simple_format(@brewery.description) %>
        <h1>Beers.</h1>
        <div class="row">
        <% @brewery.beers.order("is_vegan DESC, is_vegetarian DESC, RANDOM()").each do |beer| %>
        <div class="masonry__item col-md-4" style="padding-right: 15px;">
          <div class="card card-2 text-center" style=" <%= vegan_border_colour(beer) %>">
            <div class="card__top">
              <%= link_to main_beer_path(@brewery.slug, beer.slug) do %><img alt="Image" src="<%= beer.beer_image.thumb %>"><% end %>
            </div>
            <div class="card__body">
              <h4><%= beer.name %></h4></div>
            </div>
          </div>
        <% end %>
        </div>

      </div>
    </div>
  </div>
</section>
<section class="text-center space--xxs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-lg-8">
                            <h1>Nearby Breweries</h1>
                        </div>
                    </div>
                </div>
</section>
<section class="bg--secondary space--xxs">
<div class="container">
<% if @brewery.geocoded? %>
<div class="row">
  <% @brewery.nearbys(100).each do |brewery| %>
            <div class="masonry__item col-md-3" style="padding-right: 15px;">
          <div class="card card-2 text-center">
            <div class="card__top">
              <%= link_to main_brewery_path(brewery.slug) do %><img alt="Image" src="<%= brewery.brewery_logo.thumb %>"><% end %>
            </div>
            <div class="card__body">
              <h4><%= brewery.name %></h4></div>
            </div>
          </div>
                    
  <% end %>
  </div>
<% end %>
</div>
            </section>