config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :beers
    resources :beer_likes
    resources :breweries

    root to: "users#index"
  end

  resources :beers do
    resources :comments, only: [:create, :index, :destroy]
    member do
      get :like, :unlike
    end
  end
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :breweries

  resources :users, only: [:show], as: "/users/{:username}", as: "show_profile"


  match '/clear' => 'brewery_admin#clear', :via => 'get'
  match '/search' => "pages#search", :via => 'get', :as => "search"
  
  match '/:id' => "breweries#show", :via => 'get', :as => "main_brewery"
  match '/:brewery/beer/:id' => "beers#show", :via => 'get', :as => "main_beer"
  match '/:brewery/admin' => 'pages#index', :via => 'get'
  match '/:brewery/admin/:token' => "brewery_admin#index", :via => 'get', :as => "brewery_admin"
  match '/:brewery/admin/:beer/edit/:token' => "brewery_admin#edit", :via => 'get', :as => "brewery_edit"
 

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/beer.rb
class Beer < ApplicationRecord
    has_many :likers, foreign_key: "beer_id", class_name: "BeerLike", dependent: :destroy
    before_save :update_beer_slug
    

    mount_uploader :beer_image, BeerImageUploader, mount_on: :beer_image_file_name
    belongs_to :brewery

    has_many :comments, dependent: :destroy

    

    searchkick

    def search_data
        attributes.merge(
          brewery_name_from_relation: self.brewery_name_from_relation
        )
      end
      
      def brewery_name_from_relation
        self.brewery.name
      end

    def update_beer_slug
        self.slug = "#{name.parameterize}"
    end

end

app/controllers/admin/beers_controller.rb
module Admin
  class BeersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Beer.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Beer.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:update, :edit, :destroy, :like, :unlike, :liked?]
  before_action :set_beer_show, only: [:show]
  before_action :must_be_admin, only: [:edit, :new]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all.order("is_vegan DESC, is_vegetarian DESC, RANDOM()").page(params[:page]).per(12)
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @similar_beers = Beer.where(style: @beer.style, is_vegan: true).where.not(id: @beer.id).order("RANDOM()").limit(4)
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to main_beer_path(@beer.brewery.slug, @beer.slug), notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        if params[:commit] === "Update Details"
          format.html { redirect_to brewery_admin_path(session[:brewery], session[:token]), notice: 'Beer was successfully updated.' }
        end
        format.html { redirect_to main_beer_path(@beer.brewery.slug, @beer.slug), notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    current_user.likes.build(beer_id: @beer.id).save
    redirect_to main_beer_path(@beer.brewery.slug, @beer.slug)
  end

  def unlike
    @like = current_user.likes.where(user_id: current_user.id, beer_id: @beer.id)
    current_user.likes.delete(@like)
    redirect_to main_beer_path(@beer.brewery.slug, @beer.slug)
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_beer
      @beer = Beer.find_by(id: params[:id])
    end

    def set_beer_show
      @brewery = Brewery.find_by(slug: params[:brewery])
      @beer = Beer.find_by(slug: params[:id], brewery_id: @brewery.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :style, :abv, :description, :beer_image, :is_vegan, :is_vegetarian, :filtered, :bootle_conditioned, :can_conditioned, :organic, :gluten_free, :alcohol_free, :serving_temp, :brewery_id, :brewery_confirmed, :brewery_confirmed_at)
    end

    def must_be_admin
      unless current_user && current_user.admin?
        redirect_to new_user_session_path
      end
    end
end

app/helpers/beers_helper.rb
module BeersHelper
    def liked
        current_user.likes.where(beer_id: @beer.id).exists?
    end
end

app/views/beers/_beer-index.html.erb
<div class="col-md-4 masonry__item">
                                <div class="card card-2 text-center">
                                    <div class="card__top">
                                        <%= link_to main_beer_path(@beers.brewery.slug, @beers.slug) do %>
                                          <img alt="Image" src="<%= beer.beer_image.thumb %>" style="<%= vegan_border_colour(beer) %>">
                                        <% end %>
                                    </div>
                                    <div class="card__body">
                                      <%= link_to main_beer_path(beer.brewery.slug, beer.slug) do %>
                                        <h4><%= beer.name %></h4> <span class="type--fade"><%= beer.brewery.name %></span>
                                      <% end %>
                                    </div>
                                </div>
                            </div>

app/views/beers/_beer-show-sidebar.html.erb
<img src="<%= @beer.beer_image.thumb %>" alt="<%= @beer.name %>, <%= @beer.brewery.name %>" class="img-thumbnail beer-img <%= vegan_border_colour(@beer) %>">

<div class="likes-circle">
<% if user_signed_in? %>
  <% if liked %>
    <%= link_to unlike_beer_path(@beer),
                          id: "like_#{@beer.id}",
                          class: "glyphicon glyphicon-heart" do %>
                            <i class="fas fa-heart" style="color: #c0392b"> </i> <%= @beer.likers.count %>
                          <% end %>
  <% else %>
    <%= link_to like_beer_path(@beer),
                          id: "like_#{@beer.id}",
                          class: "glyphicon glyphicon-heart-empty" do %>
                            <i class="fas fa-heart"> </i> <%= @beer.likers.count %>
                          <% end %>
  <%end%>
<% else %>
  <i class="fas fa-heart" style="color: #c0392b"></i> <%= @beer.likers.count %>
<% end %>
</div>

      <div class="sidebar">
        <div class="sidebar-title">
          <%= @beer.name %>
        </div>
      </div>
      <div class="sidebar-item-container">
        <div class="sidebar-item beer-style">
            <%= @beer.style %>
          </div>

          <div class="sidebar-item">
            <%= @beer.abv %>% Alc
          </div>

          <div class="sidebar-item">
            <%= @beer.brewery.name %>
          </div>
        </div>

app/views/beers/_form.html.erb
<%= form_with(model: beer, local: true) do |form| %>
  <% if beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :beer_name %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style, id: :beer_style %>
  </div>

  <div class="field">
    <%= form.label :abv %>
    <%= form.text_field :abv, id: :beer_abv %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :beer_description %>
  </div>

  <div class="field">
    <%= form.label :beer_image %>
    <%= form.file_field :beer_image, id: :brewery_brewery_logo %>
  </div>

  <div class="field">
    <%= form.label :is_vegan %>
    <%= form.check_box :is_vegan, id: :beer_is_vegan %>
  </div>

  <div class="field">
    <%= form.label :is_vegetarian %>
    <%= form.check_box :is_vegetarian, id: :beer_is_vegetarian %>
  </div>

  <div class="field">
    <%= form.label :filtered %>
    <%= form.check_box :filtered, id: :beer_filtered %>
  </div>

  <div class="field">
    <%= form.label :bootle_conditioned %>
    <%= form.check_box :bootle_conditioned, id: :beer_bootle_conditioned %>
  </div>

  <div class="field">
    <%= form.label :can_conditioned %>
    <%= form.check_box :can_conditioned, id: :beer_can_conditioned %>
  </div>

  <div class="field">
    <%= form.label :organic %>
    <%= form.check_box :organic, id: :beer_organic %>
  </div>

  <div class="field">
    <%= form.label :gluten_free %>
    <%= form.check_box :gluten_free, id: :beer_gluten_free %>
  </div>

  <div class="field">
    <%= form.label :alcohol_free %>
    <%= form.check_box :alcohol_free, id: :beer_alcohol_free %>
  </div>

  <div class="field">
    <%= form.label :serving_temp %>
    <%= form.text_field :serving_temp, id: :beer_serving_temp %>
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :brewery_id %>
      <%= form.text_field :brewery_id, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<div class="main-container">
<section class="space--xs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>Edit Beer</h1>
                        </div>
                    </div>
                </div>
</section>
<section class="space--xs">
    <div class="container">
        <%= render 'form', beer: @beer %>
    </div>
</section>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<%- title "Which of these beers are vegan?" %>
<div class="main-container">
  <%= render 'layouts/searchbar' %>

  <section class="space--xxs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>Beers</h1>
                            <ol class="breadcrumbs">
                                <li><a href="#">Home</a></li>
                                <li>Beers</li>
                            </ol></div>
                    </div>
                </div>
            </section>

            <section class="bg--secondary space--xxs">
                <div class="container">
                <%= paginate(@beers) %>
                    <div class="masonry">
                        <div class="masonry__container row masonry--active">
                        <% @beers.each do |beer| %>
                            <div class="col-md-4 masonry__item">
                                <div class="card card-2 text-center">
                                    <div class="card__top">
                                        <%= link_to main_beer_path(beer.brewery.slug, beer.slug) do %>
                                          <img alt="Image" src="<%= beer.beer_image.thumb %>" style="<%= vegan_border_colour(beer) %>">
                                        <% end %>
                                    </div>
                                    <div class="card__body">
                                      <%= link_to main_beer_path(beer.brewery.slug, beer.slug) do %>
                                        <h4><%= beer.name %></h4> <span class="type--fade"><%= beer.brewery.name %></span>
                                      <% end %>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                        </div>
                    </div>
                    <%= paginate(@beers) %>
                </div>
            </section>

            

app/views/beers/new.html.erb
<div class="main-container">
<section class="space--xs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>New Beer</h1>
                        </div>
                    </div>
                </div>
</section>
<section class="space--xs">
    <div class="container">
        <%= render 'form', beer: @beer %>
    </div>
</section>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<%- title "Is #{@beer.name} by #{@beer.brewery.name} Vegan?" %>
<div class="main-container">
  <%= render 'layouts/searchbar' %>

  <section class="space--xxs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1><%= @beer.name %> by <%= @beer.brewery.name %></h1>
                            <ol class="breadcrumbs">
                                <li><a href="#">Home</a></li>
                                <li><%= link_to "Breweries", breweries_path %></li>
                                <li><%= link_to @beer.brewery.name, main_brewery_path(@beer.brewery.slug) %></li>
                                <li><%= link_to @beer.name, main_beer_path(@beer.brewery.slug, @beer.slug) %></li>
                            </ol>
                            </div>
                    </div>
                </div>
            </section>

<section class="bg--secondary space--xxs">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-lg-3">
        <div class="card card-2 text-center" style="margin-bottom: 3em; <%= vegan_border_colour(@beer) %>">
          <div class="card__top">
            <a href="#"> <img alt="Image" src="<%= @beer.beer_image.thumb %>"> </a>
          </div>
        </div>
        <div class="text-block side-bar-info">
<% if user_signed_in? %>
  <% if liked %>
    <%= link_to unlike_beer_path(@beer),
                          id: "like_#{@beer.id}",
                          class: "glyphicon glyphicon-heart" do %>
                            <i class="fas fa-heart" style="color: #c0392b"> </i> <%= @beer.likers.count %>
                          <% end %>
  <% else %>
    <%= link_to like_beer_path(@beer),
                          id: "like_#{@beer.id}",
                          class: "glyphicon glyphicon-heart-empty" do %>
                            <i class="fas fa-heart"> </i> <%= @beer.likers.count %>
                          <% end %>
  <%end%>
<% else %>
  <i class="fas fa-heart" style="color: #c0392b"></i> <%= @beer.likers.count %>
<% end %>
</div>
        <% if @beer.brewery_confirmed %>
          <div class="text-block side-bar-info">
              <i class="fas fa-check"></i> Brewery Confirmed
          </div>
        <% end %>
        <% if @beer.is_vegan %>
          <div class="text-block side-bar-info" style="margin-top: -0.5em;">
              🌱 Vegan
          </div>
        <% elsif @beer.is_vegetarian %>
          <div class="text-block side-bar-info" style="margin-top: -0.5em;">
              <span class="vegetarianicon">Ⓥ</span> Vegetarian
          </div>
         <% else %>
          <div class="text-block side-bar-info" style="margin-top: -0.5em;">
              <i class="fas fa-times"></i> Not Vegan
          </div>
        <% end %>
        <div class="text-block side-bar-info">
          <h5>Style</h5>
          <hr/>
          <p> <%= @beer.style %> </p>
        </div>
        <div class="text-block side-bar-info">
          <h5>ABV</h5>
          <hr/>
          <p> <%= @beer.abv %>%</p>
        </div>
      </div>
      <div class="col-md-8 col-lg-9">
        <div class="beer-description"><%= simple_format(@beer.description) %></div>
        <section class="switchable space--xxs">
                <div class="container">
                    <div class="row justify-content-between">
                        <div class="switchable__text col-md-12">
                            <ul class="accordion accordion-1 accordion--oneopen">
                                <li>
                                    <div class="accordion__title"><i class="fas fa-list-ul"> </i> <span class="h5">Ingredients</span> </div>
                                    <div class="accordion__content">
                                    <% if @beer.ingredients.present? %>
                                      <p class="lead"><% @beer.ingredients %></p>
                                    <% else %>
                                        <p class="lead">No ingredients available</p>
                                    <% end %>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>
      </div>
    </div>
  </div>
</section>
<section class="text-center space--xxs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-lg-8">
                            <h1>Other <%= @beer.style %> Vegan Beers</h1>
                        </div>
                    </div>
                </div>
</section>
<section class="bg--secondary space--xxs">
<div class="container">
<div class="row">
<% @similar_beers.each do |similar_beer| %>
            <div class="masonry__item col-md-3" style="padding-right: 15px;">
          <div class="card card-2 text-center">
            <div class="card__top">
              <%= link_to main_beer_path(similar_beer.brewery.slug, similar_beer.slug) do %> <img alt="Image" src="<%= similar_beer.beer_image.thumb %>"><% end %>
            </div>
            <div class="card__body">
              <h4><%= similar_beer.name %></h4></div>
            </div>
          </div>
  <% end %>
  </div>
  </div>
  </section>