config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :beers
    resources :beer_likes
    resources :breweries

    root to: "users#index"
  end

  resources :beers do
    resources :comments, only: [:create, :index, :destroy]
    member do
      get :like, :unlike
    end
  end
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :breweries

  resources :users, only: [:show], as: "/users/{:username}", as: "show_profile"


  match '/clear' => 'brewery_admin#clear', :via => 'get'
  match '/search' => "pages#search", :via => 'get', :as => "search"
  
  match '/:id' => "breweries#show", :via => 'get', :as => "main_brewery"
  match '/:brewery/beer/:id' => "beers#show", :via => 'get', :as => "main_beer"
  match '/:brewery/admin' => 'pages#index', :via => 'get'
  match '/:brewery/admin/:token' => "brewery_admin#index", :via => 'get', :as => "brewery_admin"
  match '/:brewery/admin/:beer/edit/:token' => "brewery_admin#edit", :via => 'get', :as => "brewery_edit"
 

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/brewery_admin_controller.rb
class BreweryAdminController < ApplicationController
    before_action :authenticate_brewery!, except: [:clear]

    def index
    end

    def edit
        @beer = Beer.find_by(brewery_id: @brewery_token.id, slug: params[:beer])
        @beer.brewery_confirmed = true
        @beer.brewery_confirmed_at = Date.today
    end

    def clear
        reset_session
        redirect_to root_path
    end
end

app/helpers/brewery_admin_helper.rb
module BreweryAdminHelper
end

app/views/brewery_admin/_form.html.erb
<%= form_with(model: @beer, local: true) do |form| %>
  <% if beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :beer_name %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style, id: :beer_style %>
  </div>

  <div class="field">
    <%= form.label :abv %>
    <%= form.text_field :abv, id: :beer_abv %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :beer_description %>
  </div>

  <div class="field">
    <%= form.label :beer_image %>
    <%= form.file_field :beer_image, id: :brewery_brewery_logo %>
  </div>

  <div class="field">
    <%= form.label :is_vegan %>
    <%= form.check_box :is_vegan, id: :beer_is_vegan %>
  </div>

  <div class="field">
    <%= form.label :is_vegetarian %>
    <%= form.check_box :is_vegetarian, id: :beer_is_vegetarian %>
  </div>

  <div class="field">
    <%= form.label :organic %>
    <%= form.check_box :organic, id: :beer_organic %>
  </div>

  <div class="field">
    <%= form.label :gluten_free %>
    <%= form.check_box :gluten_free, id: :beer_gluten_free %>
  </div>

  <div class="field">
    <%= form.label :alcohol_free %>
    <%= form.check_box :alcohol_free, id: :beer_alcohol_free %>
  </div>

  <%= form.hidden_field :brewery_confirmed, value: true %>
  <%= form.hidden_field :brewery_confirmed_at, value: Date.today %>
  <br />
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brewery_admin/_quick-edit.html.erb
<%= form_with(model: beer, local: true) do |form| %>
  <% if beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :is_vegan %>
    <%= form.select :is_vegan, [['Yes', true], ['No', false]] %>
  </div>

  <div class="field">
    <%= form.label :is_vegetarian %>
    <%= form.select :is_vegetarian, [['Yes', true], ['No', false]] %>
  </div>

  <%= form.hidden_field :brewery_confirmed, value: true %>
  <%= form.hidden_field :brewery_confirmed_at, value: Date.today %>
  <br />

  <div class="actions">
    <%= form.submit "Update Details" %>
  </div>
<% end %>

app/views/brewery_admin/edit.html.erb
<div class="main-container">
<section class="space--xs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>Edit Beer</h1>
                        </div>
                    </div>
                </div>
</section>
<section class="space--xs">
    <div class="container">
        <%= render 'form', beer: @beer %>
    </div>
</section>

app/views/brewery_admin/index.html.erb
<div class="main-container">
  <%= render 'layouts/searchbar' %>

  <section class="space--xs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1><%= @brewery_token.name %> Admin</h1>
                            <hr> </div>
                    </div>
                </div>
            </section>
<section class="bg--secondary">
                <div class="container">
                    <div class="masonry">
                        <div class="masonry__container row masonry--active">
                        <% @brewery_token.beers.each do |beer| %>
                            <div class="col-md-4 masonry__item">
                                <div class="card card-2 text-center">
                                    <div class="card__top">
                                          <img alt="Image" src="<%= beer.beer_image.thumb %>">
                                    </div>
                                    <div class="card__body">
                                        <h4><%= beer.name %></h4>
                                        <hr>
                                    <% if !beer.brewery_confirmed %>
                                      
                                      <h4> Quick Edit </h4>
                                      <%= render 'quick-edit', beer: beer %>
                                      <% else %>
                                      <br />
                                      <h6>Confirmed: <%= beer.brewery_confirmed_at.strftime("%d/%m/%Y") %></h6>
                                      <% end %>
                                      <hr>
                                      <%= link_to brewery_edit_path(beer.brewery.slug, beer.slug), class: "btn btn--sm type--uppercase" do %>
                                      <span class="btn__text">
                                    Edit all details
                                </span>
                                <% end %>
                                <%= link_to main_beer_path(beer.brewery.slug, beer.slug), class: "btn btn--sm type--uppercase" do %>
                                      <span class="btn__text">
                                    View
                                </span>
                                <% end %>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                        </div>
                    </div>
                </div>
            </section>


<%= session[:brewery_id] %>