config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :beers
    resources :beer_likes
    resources :breweries

    root to: "users#index"
  end

  resources :beers do
    resources :comments, only: [:create, :index, :destroy]
    member do
      get :like, :unlike
    end
  end
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :breweries

  resources :users, only: [:show], as: "/users/{:username}", as: "show_profile"


  match '/clear' => 'brewery_admin#clear', :via => 'get'
  match '/search' => "pages#search", :via => 'get', :as => "search"
  
  match '/:id' => "breweries#show", :via => 'get', :as => "main_brewery"
  match '/:brewery/beer/:id' => "beers#show", :via => 'get', :as => "main_beer"
  match '/:brewery/admin' => 'pages#index', :via => 'get'
  match '/:brewery/admin/:token' => "brewery_admin#index", :via => 'get', :as => "brewery_admin"
  match '/:brewery/admin/:beer/edit/:token' => "brewery_admin#edit", :via => 'get', :as => "brewery_edit"
 

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="text-center space--sm footer-5">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div>
                                <ul class="social-list list-inline list--hover">
                                    <li><a href="#"><i class="fab fa-google-plus-square"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter-square"></i></a></li>
                                    <li><a href="#"><i class="fab fa-facebook-square"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                </ul>
                            </div>
                            <div> <span class="type--fine-print">Made in United Kingdom</span> <span class="footer-flag">🇬🇧</span> </div>
                            <div> <span class="type--fine-print">© <span class="update-year"></span> IsItVeganBeer.com</span></div>
                        </div>
                    </div>
                </div>
            </footer>
            </div>

app/views/layouts/_navbar.html.erb
<div class="nav-container">
            <div>
                <div class="bar bar--sm visible-xs bg--dark">
                    <div class="container">
                        <div class="row">
                            <div class="col-8 col-md-2 Aligner">
                                <%= link_to root_path do %>
                                <div class="row logo-style mobile-logo">
                                <div class="logo_icon">🍺 </div>
                                <div class="logo_name">Is It Vegan Beer?</div>
                                </div>
                                <% end %>
                            </div>
                            <div class="col-4 col-md-10 text-right Aligner">
                                <a href="#" class="hamburger-toggle" data-toggle-class="#menu1;hidden-xs hidden-sm"><i class="fas fa-bars"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <nav id="menu1" class="bar bar-1 hidden-xs bg--dark">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-3 hidden-xs col-md-4 Aligner">
                                <div class="bar__module">
                                <%= link_to root_path do %>
                                  <div class="row logo-style">
                                    <div class="logo_icon">🍺 </div>
                                    <div class="logo_name">Is It Vegan Beer?</div>  
                                  </div>
                                  <% end %> 
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-12 text-right text-left-xs text-left-sm">
                                <div class="bar__module">
                                    <ul class="menu-horizontal text-left">
                                        <li>
                                            <%= link_to "Beers", beers_path %>
                                        </li>
                                        <li>
                                            <%= link_to "Breweries", breweries_path %>
                                        </li>
                                    <% if user_signed_in? %>
                                      <% if current_user.try(:admin?) %>
                                        <li>
                                            <%= link_to "New Beer", new_admin_beer_path %>
                                        </li>
                                        <li>
                                            <%= link_to "New Brewery", new_admin_brewery_path %>
                                        </li>
                                      <% end %>
                                    <% end %>
                                    </ul>
                                </div>
                                <div class="bar__module">
                                 <% if user_signed_in? %>
                                 <li class="dropdown btn btn--sm type--uppercase" style="transform: none; -webkit-transform: none;"> <span class="dropdown__trigger btn__text">
                                        My Account
                                    </span>
                                            <div class="dropdown__container">
                                                <div class="container">
                                                    <div class="row">
                                                        <div class="dropdown__content col-lg-2">
                                                            <ul class="menu-vertical">
                                                                <li><%= link_to "Show Profile", show_profile_path(current_user.username) %></li>
                                                                <hr/>
                                                                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                                                                <% if current_user.try(:admin?) %>
                                                                <hr/>
                                                                <li><%= link_to "Admin", admin_root_path %></li>
                                                                <% end %>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>

                                    <%= link_to destroy_user_session_path, method: :delete, class: "btn btn--sm btn--primary type--uppercase" do %>
                                    <span class="btn__text">
                                    Sign Out
                                    <% end %>
                                </span> </a>
                                <% elsif session[:token].present? %>
                                    <%= link_to brewery_admin_path(session[:brewery], session[:token]), class: "btn btn--sm type--uppercase" do %><span class="btn__text">
                                    Brewery Admin
                                </span> <% end %>
                                    <%= link_to clear_path, class: "btn btn--sm btn--primary type--uppercase" do %> <span class="btn__text">
                                    Sign Out
                                </span> <% end %>
                                 <% else %>
                                    <%= link_to new_user_session_path, class: "btn btn--sm type--uppercase" do %><span class="btn__text">
                                    Login
                                </span> <% end %>
                                    <%= link_to new_user_registration_path, class: "btn btn--sm btn--primary type--uppercase" do %> <span class="btn__text">
                                    Sign Up
                                </span> <% end %>
                                <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>

app/views/layouts/_searchbar.html.erb
            <section class="text-center bg--primary space--xxs">
                <div class="container">
                    <form class="row justify-content-center" action="/search" style="margin-left: 0; margin-right: 0;">
                        <div class="col-lg-6 col-md-8"> <input class="validate-required validate-email" type="text" name="query" placeholder="Search beers and breweries"> </div>
                        <div class="col-lg-2 col-md-4"> <button type="submit" class="btn btn--secondary search-button-text">Search</button> </div>
                        <div style="position: absolute; left: -5000px" aria-hidden="true"> <input type="text" name="b_77142ece814d3cff52058a51f_f300c9cce8" tabindex="-1" value=""> </div>
                    </form>
                </div>
            </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? content_for(:title) : "Is It Vegan Beer? Vegan & Vegatarian Friendly Beer List" %></title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Expires" content="30">
    <meta name="google" value="notranslate">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="google-site-verification" content="yKCloeQlLLmJ-WHlTTPnyZFBtZBA_PSG5s-fE5mQofk" />
  </head>

  <body>

  
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= javascript_include_tag "scripts", "data-turbolinks-track" => true  %> 
  </body>
</html>